### ISSUE TITLE
2.2.5 breaks SliderPicker active state

### ISSUE THREAD

**Issue by t1mmen** [casesandberg/react-color#209]
With 2.2.5's release, the `SlidePicker`'s active state no longer triggers on the active swatch.

Screenshots indicating the problem. The middle value is selected in both examples:
#### 2.2.2:
![screen shot 2016-08-24 at 13 14 45](https://cloud.githubusercontent.com/assets/192263/17946395/fccb70fa-69fc-11e6-8341-545825983bce.png)

#### 2.2.5
![screen shot 2016-08-24 at 13 08 26](https://cloud.githubusercontent.com/assets/192263/17946416/123fb504-69fd-11e6-8059-a6ed6d9b69b8.png)

It doesn't matter if I pass in hex, hsl or rgb values as the `color` prop. This could perhaps be related to https://github.com/casesandberg/react-color/issues/28, where picking the last swatch doesn't activate?

**Comment by casesandberg** [comment]
Sorry about the regression there, this has been fixed if you update to `react-color@2.2.6`

**Comment by t1mmen** [comment]
Thank you for the quick fix, much appreciated!

**Comment by t1mmen** [comment]
@casesandberg Sorry, I'm still experiencing this issue with 2.2.6. Assuming the demo at http://casesandberg.github.io/react-color/ is updated too, the issue is demonstrated there.

**Comment by casesandberg** [comment]
Sorry, the documentation website didnt get updated for some reason. It is updated now and reflects that it is indeed working: http://casesandberg.github.io/react-color/

Could you try installing it again and see if you still have issues?

**Comment by t1mmen** [comment]
Confirming this works now with `2.2.7`. Not clear on why I couldn't get this working on `2.2.6` (I uninstalled, re-installed, re-started webpack, etc to no avail). Thanks!
