### ISSUE TITLE
cannot bundle with webpack since 1.3.1

### ISSUE THREAD

**Issue by TinOo512** [casesandberg/react-color#76]
Hi I can't use your module since the 1.3.1 version. I get this error with the latest version which is 1.3.3.

It appear to be since the migration to Babel 6.0 here 0d1c7d2c92ee9963e52bab46276312d57d69d845.

```
ERROR in ./~/react-color/modules/react-material-design/lib/components/Tabs.js
Module not found: Error: Cannot resolve module 'lodash/lang/isString' in /home/kontest/workspace/game-livebuilder/node_modules/react-color/modules/react-material-design/lib/components
 @ ./~/react-color/modules/react-material-design/lib/components/Tabs.js 11:16-47

ERROR in ./~/react-color/modules/react-material-design/lib/components/Link.js
Module not found: Error: Cannot resolve module 'lodash/lang/isString' in /home/kontest/workspace/game-livebuilder/node_modules/react-color/modules/react-material-design/lib/components
 @ ./~/react-color/modules/react-material-design/lib/components/Link.js 9:16-47
```

Maybe you should also tag on github that's way it will be easier to track versions :)

**Comment by slestang** [comment]
I have the same error if I do:
```js
import { SketchPicker } from 'react-color'
```
But if I import the component with the full path, it's working:
```js
import SketchPicker from 'react-color/lib/components/SketchPicker'
...
```

Far from being a nice/clean solution.

**Comment by casesandberg** [comment]
Sorry guys, updating this now back to the old import method which should fix this.

**Comment by casesandberg** [comment]
I reverted the export here: https://github.com/casesandberg/react-color/commit/086b13969faa806dab3a983b2df32d9450717ba9

You can use the old style of import by upgrading to `react-color@1.3.4`

**Comment by slestang** [comment]
I still have the same error in 1.3.4 if I do the import like this:
```js
import { SketchPicker } from 'react-color'
```
