### ISSUE TITLE
upgrade to reactcss@0.4.3 

### ISSUE THREAD

**Issue by abhishiv** [casesandberg/react-color#89]
This would finally get rid of entire lodash.js being included into webpack and maybe browserify.

related casesandberg/reactcss#28

**Comment by casesandberg** [comment]
Done! `react-color@1.3.7`

**Comment by abhishiv** [comment]
Hey @casesandberg 

Sorry for not responding earlier. This works, however I'm still not able to get rid of the single lodash dependency from my build.

The problem seems to be in [modules/react-material-design/src/components/Link.js](https://github.com/casesandberg/react-color/blob/8e1f43dfb97d9920bba8eea4b0a5e682cf320e68/modules/react-material-design/src/components/Link.js) and [modules/react-material-design/src/components/Tabs.js](https://github.com/casesandberg/react-color/blob/8e1f43dfb97d9920bba8eea4b0a5e682cf320e68/modules/react-material-design/src/components/Link.js)

Are these maintained by you?

**Comment by ksonnad** [comment]
I can corroborate, here's webpack-analyse output for the lodash/index module: https://www.dropbox.com/s/jidzk0bjuuysbm1/Screenshot%202016-03-29%2012.10.36.png?dl=0
